### ISSUE TITLE
Where are the gloss data and embedding data?

### ISSUE THREAD

**Issue by cnut1648** [SapienzaNLP/multilabel-wsd#1]
Hi, I read through your paper and it is an very interesting work! Well done!

I have one question, where are the gloss and embedding data?
I can run `preprocess_raganato.sh` on the [dataset downloaded from here](http://lcl.uniroma1.it/wsdeval/home), but I couldn't find the gloss and embedding data required by `preprocess_glosses.sh` and `preprocess_sense_embeddings.sh`. Would you mind sharing with us the data?

Thanks!

**Comment by c-simone** [comment]
Hi, thank you for your interest!

You can find the additional training data with glosses and examples [here](https://github.com/SapienzaNLP/ewiser/tree/master/res/corpora/training/orig).

As for the embeddings, this is something that didn't actually make it in the paper. I experimented with including sense embeddings such as [SenseEmBERT](http://sensembert.org/) (Scarlini et al., 2020) and [LMMS](https://github.com/danlou/LMMS) (Loureiro and Jorge, 2019), but I didn't find any significant improvement. I suspect they can be beneficial (see EWISER by Bevilacqua et al., 2019), so I left the code in the repo.

Let me know if you have any other questions!
