### ISSUE TITLE
where are the data?

### ISSUE THREAD

**Issue by Stubborn-z** [SapienzaNLP/multilabel-wsd#3]
Hi, I read through your paper and it is an very interesting work!

But I have one question, where are the data?and where's the requirements.txt?

Thanks!

**Comment by chenyazhen** [comment]
Hi,I‘m also  intesested in your paper,but i can't find  the data and requirements.txt.Thanks!

**Comment by c-simone** [comment]
Hello, thank you for your interest in our work.

I've updated the README with links to where to download the data.
